name: Test PR on dev branch
run-name: Testing PR by ${{ github.actor }}
on:
  pull_request:
    branches:
      - dev
      - develop
jobs:
  say_hello:
    runs-on: ubuntu_latest
    env:
      FIRST_NAME: Jaehwan
    steps:
      - env:
          LAST_NAME: Hyun
        run: |
          echo "My first name is $FIRST_NAME"
      - run: echo "My last name is $LAST_NAME"
      - run: echo "My full name is $FIRST_NAME $LAST_NAME"
        with:
          FIRST_NAME: JAEHWAN
          LAST_NAME: HYUN
